import logging

from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .nodes_sd3 import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_SD3
from .nodes_sd3 import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_SD3
from .nodes_sdxl import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_SDXL
from .nodes_sdxl import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_SDXL
from .nodes_anima import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_ANIMA
from .nodes_anima import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_ANIMA

NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_SD3)
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_SDXL)
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_ANIMA)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_SD3)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_SDXL)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_ANIMA)

try:
    from .nodes_ltx import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_LTX
    from .nodes_ltx import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_LTX
    NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_LTX)
    NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_LTX)
except Exception as e:
    logging.getLogger(__name__).warning(f"LTX training nodes failed to load: {e}")

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]